import type { Metadata } from "next";
import { Inter, Poppins, Public_Sans } from "next/font/google";
import "./globals.css";
import "@/style/main.scss";

const interFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const publicSans = Public_Sans({
  variable: "--font-public-sans",
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

const poppinsFont = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${interFont.variable} ${poppinsFont.variable} ${publicSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
